### ISSUE TITLE
Unable to create new API

### ISSUE THREAD

**Issue by divix1988** [laminas-api-tools/api-tools-admin#52]
### Bug Report

Latest master code is used.

#### Summary

Unable to create ANY API module via: http://localhost/laminas_app/api-tools/ui

#### Current behavior

```
Fatal error: Uncaught Laminas\ModuleManager\Exception\RuntimeException: Module (ApplicationTest) could not be initialized. in E:\RZECZY_ADAMA\_XAMPP\xampp-7.4\htdocs\laminas_app\vendor\laminas\laminas-modulemanager\src\ModuleManager.php:202 

Stack trace: #0 E:\RZECZY_ADAMA\_XAMPP\xampp-7.4\htdocs\laminas_app\vendor\laminas\laminas-modulemanager\src\ModuleManager.php(174): Laminas\ModuleManager\ModuleManager->loadModuleByName(Object(Laminas\ModuleManager\ModuleEvent)) #1 
E:\RZECZY_ADAMA\_XAMPP\xampp-7.4\htdocs\laminas_app\vendor\laminas\laminas-modulemanager\src\ModuleManager.php(96): Laminas\ModuleManager\ModuleManager->loadModule('ApplicationTest') #2 E:\RZECZY_ADAMA\_XAMPP\xampp-7.4\htdocs\laminas_app\vendor\laminas\laminas-eventmanager\src\EventManager.php(321): Laminas\ModuleManager\ModuleManager->onLoadModules(Object(Laminas\ModuleManager\ModuleEvent)) #3 
E:\RZECZY_ADAMA\_XAMPP\xampp-7.4\htdocs\laminas_app\vendor\laminas\laminas-eventmanager\src\EventManager.php(170): Laminas\EventManager\EventManager->triggerListener in E:\RZECZY_ADAMA\_XAMPP\xampp-7.4\htdocs\laminas_app\vendor\laminas\laminas-modulemanager\src\ModuleManager.php on line 202
```

#### How to reproduce

-Go to: `/api-tools/ui`
-Click on Create API 
-Type any name
-Click Create.

#### Expected behavior

New API should be created.

**Comment by weierophinney** [comment]
Fixed with #79
